services:
  - type: web
    name: cathealth-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/python/requirements.txt
    startCommand: cd backend/python && python main1.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0